# Generated by Django 6.0.1 on 2026-01-13 00:49

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('volunteers', 'Category')
    categories = [
        {'name': 'Tutoring', 'slug': 'tutoring'},
        {'name': 'Food Prep', 'slug': 'food-prep'},
        {'name': 'Senior Support', 'slug': 'senior-support'},
        {'name': 'Sports', 'slug': 'sports'},
        {'name': 'Other', 'slug': 'other'},
    ]
    for category_data in categories:
        Category.objects.get_or_create(**category_data)


def remove_default_categories(apps, schema_editor):
    Category = apps.get_model('volunteers', 'Category')
    Category.objects.filter(slug__in=[
        'tutoring', 'food-prep', 'senior-support', 'sports', 'other'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
